name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.21.x"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - run: go vet ./...
    - run: go test -vet=off -v ./...
    - if: matrix.os == 'ubuntu-latest'
      run: GOOS=wasip1 GOARCH=wasm go vet ./...
    - if: matrix.os == 'ubuntu-latest'
      run: GOOS=js GOARCH=wasm go vet ./...